version: '2'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: urbatek
            MYSQL_USER: urbatek
            MYSQL_PASSWORD: urb1t3k
    php:
        build: ./php-fpm
        expose:
            - "9001"
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "82:80"
        links:
            - php
            - db
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
